### PR TITLE
GitHub view for table

### PR DESCRIPTION
**Pull request by Piterden**
It is a start of the idea

### CODE REVIEW

**Comment by Piterden** [comment]
image

**Comment by RyanThompson** [comment]
Have you tested out the composer thing to bring these in? Something like a modal with a loading circle letting you know its working in the background.

**Comment by RyanThompson** [comment]
If you would please - let's keep this open as a convo / code comparison but I won't / cant merge it in obviously.

**Comment by Piterden** [comment]
Yes, please keep it for a time. I will work more with it some later.

**Comment by RyanThompson** [comment]
I like this - and am gonna stash it to use something different instead ^_^

I think you'll like what I do - but thanks for paving the way!

**Pull request closed without merging**
